### ISSUE TITLE
Add a makefile

### ISSUE THREAD

**Issue by JayWalker512** [JayWalker512/ascii_raytracer#1]
Because this project is trivial and should be trivially compiled.

**Comment by Zi7ar21** [comment]
Is this satisfactory?
```makefile
all:
gcc ascii_raytracer.c -o ascii_raytracer -lm
```

**Comment by JayWalker512** [comment]
> Is this satisfactory?
> 
> ```makefile
> all:
> gcc ascii_raytracer.c -o ascii_raytracer -lm
> ```

It sure is! I just committed this addition. Thanks!
